Assert terminator support
liquid-rust/liquid-rust pull request #25
Opened 2022-01-19 16:39 UTC by atgeller

Assert, a terminator in rust's mir, seems to be generated for under/overflow checking, as well as checking for div-by-zero. This includes supporting it essentially as a guarded goto, but also demonstrates the code needed to validate the absence of possible assert failures.

2022-01-19 19:36 UTC, nilehmann requested changes
@atgeller I just realized that no matter which optimization flags are passed to `rustc` it will always generate an assert for integer division and reminder, so we should land this before adding support for `%`.

Some comments below

2022-01-19 19:36 UTC, nilehmann commented on liquid-rust-typeck/src/checker.rs
> +        let assert = ExprKind::BinaryOp(BinOp::Eq, pred, ExprKind::Constant(liquid_rust_fixpoint::Constant::Bool(*expected)).intern()).intern();
I would go with the following as I think it'll generate a slightly simpler constraint:

```suggestion
        let assert = if cond { pred } else { pred.not() }
```

2022-01-19 19:36 UTC, nilehmann commented on liquid-rust-typeck/src/checker.rs
> +        expected: &bool,
```suggestion
        expected: bool,
```
https://rust-lang.github.io/rust-clippy/master/index.html#trivially_copy_pass_by_ref

2022-01-19 19:36 UTC, nilehmann commented on tests/neg/assert_terminator.rs
> +pub fn assert_terminator_test(a: usize, b: usize) -> usize {
You need to add test explicitly to `liquid-rust-driver/tests/pos.rs`

2022-01-19 19:36 UTC, nilehmann commented on tests/pos/assert_terminator.rs
> +pub fn assert_terminator_test(a: usize, b: usize) -> usize {
You need to add test explicitly to `liquid-rust-driver/tests/neg.rs`

2022-01-19 19:36 UTC, nilehmann commented on liquid-rust-typeck/src/checker.rs
> +        // WARNING: rust is very eager about inserting under/overflow checks, so be warned that uncommenting this will likely break everything
More than a `warning` I would add a `TODO` to make this user-configurable. We have some support for config flags here https://github.com/liquid-rust/liquid-rust/blob/main/liquid-rust-common/src/config.rs so we could make a new config to choose between both. It doesn't have to go in this PR though.

2022-01-19 19:36 UTC, nilehmann commented on liquid-rust-core/src/ir.rs
> +                write!(f, "Assert({:?} is expected to be {:?}) -> {:?}", cond, expected, target)
```suggestion
                write!(f, "assert({:?} is expected to be {:?}) -> {:?}", cond, expected, target)
```

2022-01-20 14:53 UTC, atgeller commented
I think the latest commits have resolved everything. I'll take a look at adding an option that just generates a warning/todo if set to true for now, and we can worry about threading it through later.

2022-01-20 15:01 UTC, nilehmann approved these changes
Lgtm

2022-01-24 22:22 UTC, merged